name: gncutils
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.24.0=py35_0
- cffi=1.11.5=py35_0
- cryptography=2.2.1=py35_0
- curl=7.59.0=0
- geos=3.6.2=1
- gsw=3.2.0=py35_0
- hdf4=4.2.13=0
- hdf5=1.10.1=2
- idna=2.6=py35_1
- jpeg=9b=2
- krb5=1.14.2=0
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libnetcdf=4.5.0=3
- libssh2=1.8.0=2
- netcdf4=1.3.1=py35_2
- openblas=0.2.20=7
- paramiko=2.4.1=py35_0
- pyasn1=0.4.3=py_0
- pycparser=2.18=py35_0
- pynacl=1.1.2=py35_0
- pysftp=0.2.9=py35_0
- python-dateutil=2.7.1=py_0
- six=1.11.0=py35_1
- bcrypt=3.1.3=py35_0
- blas=1.0=mkl
- certifi=2016.2.28=py35_0
- cycler=0.10.0=py35_0
- freetype=2.5.5=2
- icu=54.1=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.8.0=py35_0
- matplotlib=2.0.2=np113py35_0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.4=0
- pytz=2017.2=py35_0
- qt=5.6.2=2
- readline=6.2=2
- scipy=0.19.1=np113py35_0
- setuptools=36.4.0=py35_1
- shapely=1.5.16=py35_0
- sip=4.18=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
prefix: /Users/kerfoot/miniconda3/envs/gncutils

